### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by zniter81** [Pkmmte/CircularImageView#58]
Hi got this exception.

basically i call the below statement twice but OwnerProfilePictureURL is a different URL and i get the exception.
`Picasso.with(ma).load(ma.OwnerProfilePictureURL).resize(witdthHeight, witdthHeight).centerCrop().into(userProfileImage);`

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:714)
       at com.pkmmte.view.CircularImageView.refreshBitmapShader(CircularImageView.java:341)
       at com.pkmmte.view.CircularImageView.invalidate(CircularImageView.java:262)
       at android.widget.ImageView.setImageDrawable(ImageView.java:467)
       at com.squareup.picasso.PicassoDrawable.setPlaceholder(PicassoDrawable.java:61)
       at com.squareup.picasso.RequestCreator.into(RequestCreator.java:664)
       at com.squareup.picasso.RequestCreator.into(RequestCreator.java:601)
       at com.belvia.pyp.UI.MainActivity$9.onPostExecute(MainActivity.java:681)
       at com.belvia.pyp.UI.MainActivity$9.onPostExecute(MainActivity.java:668)
       at android.os.AsyncTask.finish(AsyncTask.java:632)
       at android.os.AsyncTask.access$600(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5944)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by rishabhsri20** [comment]
#22
