### ISSUE TITLE
When clearing the image using .setImageBitmap(null) a nullpointer exception occurs

### ISSUE THREAD

**Issue by timkoers** [Pkmmte/CircularImageView#59]
When clearing the current image using setImageBitmap(null) a nullpointer exception occurs:

java.lang.NullPointerException: 
Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:591)
at com.pkmmte.view.CircularImageView.refreshBitmapShader(CircularImageView.java:341)
at com.pkmmte.view.CircularImageView.invalidate(CircularImageView.java:262)
at android.widget.ImageView.setImageDrawable(ImageView.java:456)
at android.widget.ImageView.setImageBitmap(ImageView.java:548)

This should not happen, the default ImageView doesn't do this.

**Comment by bdipak** [comment]
+1

Is this fixed ??

**Comment by rishabhsri20** [comment]
same issue here..

**Comment by shinayser** [comment]
Is this project abandoned? This issue persists (June 17)
