### ISSUE TITLE
Crash on finish Activity.

### ISSUE THREAD

**Issue by dyguests** [Pkmmte/CircularImageView#65]
Huawei rongyao 6X

Android 7.0

I have a CircularImageView in MainAcitivy.when I finish MainAcitivyt.it crashed:

Source:

code:

```kotlin
Glide.with(root.img_avatar)
                            .load(url)
                            .placeholder(R.mipmap.ic_mine_head_default)
                            .into(root.img_avatar)
```

xml:

```xml
    <com.pkmmte.view.CircularImageView
        android:id="@+id/img_avatar"
        android:layout_width="48dp"
        android:layout_height="48dp"
        android:layout_marginLeft="8dp"
        android:layout_marginStart="8dp"
        android:contentDescription="@null"
        android:src="@mipmap/ic_mine_head_default"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        tools:background="#234"/>
```

Crash log:

```log
 java.lang.RuntimeException: Unable to destroy activity {com.lxt.app/com.lxt.app.ui.maink6.MainK6Activity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                               at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4398)
                                                               at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4417)
                                                               at android.app.ActivityThread.-wrap6(ActivityThread.java)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
                                                               at android.os.Handler.dispatchMessage(Handler.java:105)
                                                               at android.os.Looper.loop(Looper.java:156)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                            Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                               at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:815)
                                                               at com.pkmmte.view.CircularImageView.refreshBitmapShader(CircularImageView.java:341)
                                                               at com.pkmmte.view.CircularImageView.invalidate(CircularImageView.java:262)
                                                               at android.widget.ImageView.setImageDrawable(ImageView.java:521)
                                                               at com.bumptech.glide.request.target.DrawableImageViewTarget.setResource(DrawableImageViewTarget.java:22)
                                                               at com.bumptech.glide.request.target.DrawableImageViewTarget.setResource(DrawableImageViewTarget.java:10)
                                                               at com.bumptech.glide.request.target.ImageViewTarget.setResourceInternal(ImageViewTarget.java:116)
                                                               at com.bumptech.glide.request.target.ImageViewTarget.onLoadCleared(ImageViewTarget.java:86)
                                                               at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:319)
                                                               at com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(RequestTracker.java:62)
                                                               at com.bumptech.glide.RequestManager.untrack(RequestManager.java:462)
                                                               at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:449)
                                                               at com.bumptech.glide.RequestManager.clear(RequestManager.java:437)
                                                               at com.bumptech.glide.RequestManager.onDestroy(RequestManager.java:290)
                                                               at com.bumptech.glide.manager.ActivityFragmentLifecycle.onDestroy(ActivityFragmentLifecycle.java:64)
                                                               at com.bumptech.glide.manager.RequestManagerFragment.onDestroy(RequestManagerFragment.java:197)
                                                               at android.app.Fragment.performDestroy(Fragment.java:2610)
                                                               at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1128)
                                                               at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1178)
                                                               at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1160)
                                                               at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2074)
                                                               at android.app.FragmentController.dispatchDestroy(FragmentController.java:242)
                                                               at android.app.Activity.performDestroy(Activity.java:7134)
                                                               at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1158)
                                                               at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4385)
                                                               at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4417) 
                                                               at android.app.ActivityThread.-wrap6(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                               at android.os.Looper.loop(Looper.java:156) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:6523) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
```

see `Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference` and `at com.pkmmte.view.CircularImageView.refreshBitmapShader`.

**Comment by esecoder** [comment]
I have this same problem

**Comment by abspatel7** [comment]
It's toonlong time when i fetch same error... I think when u call web
service.. It takes null value else u require add library in java file

**Comment by dyguests** [comment]
fixed after refactor.(Still don't understand why,sad:( )

**Comment by esecoder** [comment]
Refactor? How do you mean? How did you refactor?

**Comment by dyguests** [comment]
@EseCoder 
I don't know. just refactor my activity from java to kotlin. and rewrite some login code. It fixed. but I don't know why!!! but it fixed. :(

Anyway. I use new image load framework : Glide.

    Glide.with(context).load(url).apply(RequestOptions.circleCropTransform()).into(imageView);

hope help u.

**Comment by Andrax92** [comment]
@EseCoder I'm running into the same problem and can't find a way to fix it. Did you find a workaround? 
apply(RequestOptions.circleCropTransform()) didn't work for me.

**Comment by esecoder** [comment]
> @EseCoder I'm running into the same problem and can't find a way to fix it. Did you find a workaround?
> apply(RequestOptions.circleCropTransform()) didn't work for me.

I used a different circle image library all together. But I think the answer above offers a solution too.

**Comment by Andrax92** [comment]
@EseCoder thank you for your quick response.

Just in case someone runs into the same issue, I finally sorted it out with this code:

`Glide.with(this).asBitmap().load(imageUrl).apply(options).into(object : CustomTarget<Bitmap>() {
                override fun onResourceReady(resource: Bitmap, transition: Transition<in Bitmap>?) {
                    binding.imgCirclePhoto.setImageBitmap(resource)
                }
                override fun onLoadCleared(placeholder: Drawable?) {
                }
            })`

Just load as bitmap and into a CustomTarget object.
